# Generated by Django 3.0.7 on 2020-12-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tortoise_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='guild',
            new_name='guilds',
        ),
    ]
