# Generated by Django 3.0.7 on 2020-10-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tortoise_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
