# Generated by Django 3.0.7 on 2020-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20201029_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='brief',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='https://cdn.discordapp.com/embed/avatars/4.png'),
        ),
    ]
