# Generated by Django 3.0.7 on 2020-12-18 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tortoise_api', '0002_auto_20201218_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tortoise_api.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tortoise_api.Invite'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'guild', 'invited_by'), ('user', 'guild')},
        ),
    ]
