# Generated by Django 3.0.7 on 2020-10-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortoise_api', '0003_auto_20201031_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.CharField(max_length=6),
        ),
    ]
