# Generated by Django 3.0.7 on 2020-10-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortoise_api', '0004_auto_20201031_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.CharField(default='', max_length=6),
        ),
    ]
