# Generated by Django 3.0.7 on 2020-11-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tortoise_api', '0005_auto_20201031_0138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
