# Generated by Django 3.2.8 on 2021-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
