# Generated by Django 3.2.3 on 2021-05-23 19:13

import django.contrib.postgres.fields
from django.db import migrations
import utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('tortoise_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='emotes',
            field=django.contrib.postgres.fields.ArrayField(base_field=utils.misc.DiscordIDField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
