# Generated by Django 3.2.3 on 2021-05-23 09:57

from django.db import migrations, models
import utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('tortoise_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='sponsors',
            field=models.JSONField(blank=True, default=utils.misc.empty_dict),
        ),
    ]
