# Generated by Django 3.2.8 on 2021-11-01 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20211101_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='event_tags',
        ),
    ]
