# Generated by Django 3.2.8 on 2021-11-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_event_type_event_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(default='Python', max_length=15),
        ),
    ]
