# Generated by Django 2.2.5 on 2019-12-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('eventimage', models.ImageField(blank=True, upload_to='img/eventimgs')),
                ('coverimage', models.ImageField(upload_to='img/bgimgs')),
                ('eventtype', models.CharField(choices=[('Coding-Challenge', 'Coding-Challenge'), ('CTF-Event', 'CTF-Event')], default='CTF-Event', max_length=17)),
                ('duedate', models.DateField()),
                ('enddate', models.DateField()),
                ('winner', models.CharField(blank=True, max_length=100)),
                ('prize', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Live', 'Live'), ('Ended', 'Ended')], default='Ended', max_length=17)),
                ('host', models.CharField(max_length=15)),
                ('task', models.CharField(max_length=50)),
                ('desc', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
                ('choice', models.CharField(choices=[('Live', 'Live'), ('Announcements', 'Announcements'), ('News', 'News')], default='Live', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('coverimage', models.ImageField(upload_to='img/bgimgs')),
                ('rating', models.FloatField(default=None)),
                ('color', models.CharField(choices=[('score yellow', 'Yellow'), ('score purple', 'Purple'), ('score pink', 'Pink'), ('score green', 'Green')], default='Yellow', max_length=12)),
                ('label', models.TextField(max_length=60)),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Incomplete', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeadCrumb1', models.CharField(max_length=20)),
                ('Span', models.CharField(blank=True, max_length=20)),
                ('HeadCrumb2', models.CharField(blank=True, max_length=20)),
                ('Slideimage', models.ImageField(upload_to='img')),
                ('Subhead', models.CharField(blank=True, max_length=50)),
                ('Note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('profilepic', models.ImageField(upload_to='img/team')),
                ('nickname', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=12)),
            ],
        ),
    ]
