# Generated by Django 3.0.7 on 2020-08-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('eventimage', models.ImageField(blank=True, upload_to='img/eventimgs')),
                ('coverimage', models.ImageField(upload_to='img/bgimgs')),
                ('eventtype', models.CharField(choices=[('Other Event', 'Other'), ('CTF Event', 'CTF-Event'), ('Team Challenge', 'Team-Challenge'), ('Coding Challenge', 'Coding-Challenge')], default='CTF-Event', max_length=17)),
                ('duedate', models.DateField()),
                ('enddate', models.DateField()),
                ('winner', models.CharField(blank=True, max_length=100)),
                ('prize', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Ended', 'Ended'), ('Upcoming', 'Upcoming')], default='Ended', max_length=17)),
                ('style', models.CharField(choices=[('dark.min.css', 'Dark'), ('dracula.min.css', 'Dracula'), ('tomorrow.min.css', 'Tomorrow'), ('night-owl.min.css', 'Night Owl'), ('codepen-embed.min.css', 'Codepen'), ('github-gist.min.css', 'Github Gist'), ('atom-one-dark.min.css', 'Atom Dark'), ('solarized-dark.min.css', 'Solarized Dark'), ('atelier-cave-dark.min.css', 'Atelier Cave'), ('tomorrow-night-blue.css', 'Tomorrow Night Blue'), ('atom-one-dark-reasonable.min.css', 'Atom Dark Reasonable')], default='default.min.css', max_length=50)),
                ('host', models.CharField(max_length=15)),
                ('task', models.CharField(max_length=50)),
                ('desc', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
                ('choice', models.CharField(choices=[('News', 'News'), ('Live', 'Live'), ('Announcements', 'Announcements')], default='Live', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField(blank=True, default=None)),
                ('extra', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeadCrumb1', models.CharField(blank=True, max_length=20)),
                ('Span', models.CharField(blank=True, max_length=20)),
                ('HeadCrumb2', models.CharField(blank=True, max_length=20)),
                ('Slideimageurl', models.URLField(blank=True)),
                ('Subhead', models.CharField(blank=True, max_length=50)),
                ('Note', models.TextField(blank=True)),
                ('button', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('profilepic', models.ImageField(upload_to='img/team')),
                ('nickname', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=12)),
            ],
        ),
    ]
