# Generated by Django 3.0.7 on 2020-08-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
