# Generated by Django 3.0.7 on 2020-08-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0002_news_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Note',
        ),
    ]
