# Generated by Django 2.2.5 on 2019-12-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0002_auto_20191208_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='invite',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='rating',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('cata yellow', 'Completed'), ('cata purple', 'Refactoring'), ('cata red', 'Started'), ('cata green', 'Upcoming')], default='Upcoming', max_length=16),
        ),
    ]
