# Generated by Django 2.2.5 on 2019-12-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0003_auto_20191212_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='prize',
            field=models.CharField(max_length=100),
        ),
    ]
