# Generated by Django 3.0.7 on 2020-10-20 21:01

import django.contrib.postgres.fields
from django.db import migrations, models
import utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0003_remove_news_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='alias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=utils.misc.empty_array, null=True, size=None),
        ),
        migrations.AddField(
            model_name='events',
            name='page_theme',
            field=models.CharField(choices=[('event-light-theme', 'Light Theme'), ('event-dark-theme', 'Dark Theme'), ('event-ares-theme', 'Ares Theme'), ('event-nemesis-theme', 'Nemesis Theme'), ('event-grass-hopper-theme.css', 'Grasshopper Theme')], default='event-light-theme', max_length=25),
        ),
    ]
