# Generated by Django 3.0.7 on 2020-10-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0005_auto_20201021_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='alias',
            new_name='sponsors',
        ),
        migrations.AlterField(
            model_name='events',
            name='host',
            field=models.CharField(max_length=100),
        ),
    ]
