# Generated by Django 3.0.7 on 2020-10-20 22:04

import django.contrib.postgres.fields
from django.db import migrations, models
import utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0006_auto_20201021_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='sponsors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=utils.misc.empty_array, null=True, size=None),
        ),
    ]
