# Generated by Django 2.2.5 on 2020-02-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0006_auto_20200221_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy',
            name='extra',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
