# Generated by Django 3.0.7 on 2020-10-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0007_auto_20201021_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='sponsors',
        ),
    ]
