# Generated by Django 2.2.5 on 2020-02-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0007_privacy_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='header',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
