# Generated by Django 2.2.5 on 2020-03-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0008_auto_20200226_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
