# Generated by Django 2.2.5 on 2020-03-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0009_delete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
