# Generated by Django 2.2.5 on 2020-04-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0011_remove_privacy_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='Slideimage',
        ),
        migrations.AddField(
            model_name='slider',
            name='Slideimageurl',
            field=models.URLField(blank=True),
        ),
    ]
