# Generated by Django 3.0.7 on 2020-07-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0012_auto_20200410_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='HeadCrumb1',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
