# Generated by Django 3.0.7 on 2020-07-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0014_auto_20200731_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='style',
            field=models.CharField(choices=[('dark.min.css', 'Dark'), ('dracula.min.css', 'Dracula'), ('tomorrow.min.css', 'Tomorrow'), ('night-owl.min.css', 'Night Owl'), ('codepen-embed.min.css', 'Codepen'), ('github-gist.min.css', 'Github Gist'), ('atom-one-dark.min.css', 'Atom Dark'), ('solarized-dark.min.css', 'Solarized Dark'), ('atelier-cave-dark.min.css', 'Atelier Cave'), ('tomorrow-night-blue.css', 'Tomorrow Night Blue'), ('atom-one-dark-reasonable.min.css', 'Atom Dark Reasonable')], default='default.min.css', max_length=50),
        ),
    ]
