# Generated by Django 3.0.7 on 2020-07-07 22:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import userdata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=6, null=True)),
                ('perks', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, default=None, max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('coverimage', models.ImageField(upload_to='img/bgimgs')),
                ('rating', models.FloatField(blank=True, default=None)),
                ('label', models.CharField(default=None, max_length=100)),
                ('brief', models.TextField(default=None)),
                ('status', models.CharField(choices=[('cata yellow', 'Completed'), ('cata purple', 'Refactoring'), ('cata red', 'Started'), ('cata green', 'Upcoming')], default='Upcoming', max_length=16)),
                ('github', models.URLField(blank=True)),
                ('invite', models.URLField(blank=True)),
                ('commits', models.IntegerField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('forks', models.IntegerField(blank=True, null=True)),
                ('contributors', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('alias', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=userdata.models.empty_array, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ServerUtils',
            fields=[
                ('guild_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('event_submission', models.BooleanField(default=False, null=True)),
                ('bug_report', models.BooleanField(default=False, null=True)),
                ('mod_mail', models.BooleanField(default=False, null=True)),
                ('suggestions', models.BigIntegerField(blank=True, null=True)),
                ('bot_status', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=userdata.models.empty_dict, null=True)),
                ('Github_Microservice', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_service_status, null=True)),
                ('Status_Microservice', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_service_status, null=True)),
                ('Tortoise_BOT', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_service_status, null=True)),
                ('Tortoise_BOT2', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_service_status, null=True)),
                ('Website', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_service_status, null=True)),
                ('Sockets', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_service_status, null=True)),
                ('API_Gateway', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_service_status, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('message_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('author_id', models.BigIntegerField()),
                ('author_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('brief', models.TextField(default=None)),
                ('status', models.CharField(default='Under Review', max_length=20)),
                ('reason', models.TextField(blank=True, default=None, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=6, null=True)),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('guild_id', models.BigIntegerField()),
                ('email', models.TextField(blank=True, null=True)),
                ('perks', models.IntegerField(blank=True, default=0, null=True)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('leave_date', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('strikes', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_strikes, null=True)),
                ('mod_mail', models.BooleanField(blank=True, default=False, null=True)),
                ('warnings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=userdata.models.empty_array, null=True, size=None)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=userdata.models.empty_array, null=True, size=None)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('member', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'unique_together': {('user_id', 'guild_id')},
            },
        ),
    ]
