# Generated by Django 2.2.5 on 2019-12-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('guild_id', models.BigIntegerField()),
                ('email', models.TextField(blank=True, null=True)),
                ('perks', models.IntegerField(blank=True, null=True)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('leave_date', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('strikes', models.TextField(blank=True, null=True)),
                ('mod_mail', models.BooleanField(blank=True, null=True)),
                ('warnings', models.TextField(blank=True, null=True)),
                ('roles', models.TextField(blank=True, null=True)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('user_id', 'guild_id')},
            },
        ),
    ]
