# Generated by Django 3.0.7 on 2020-10-28 18:56

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import utils.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('event_submission', models.BooleanField(default=False)),
                ('bug_report', models.BooleanField(default=False)),
                ('mod_mail', models.BooleanField(default=False)),
                ('suggestions', models.BooleanField(default=False)),
                ('suggestion_message_id', models.BigIntegerField(blank=True, default=0)),
                ('suggestion_channel_id', models.BigIntegerField(blank=True, default=0)),
                ('verification_channel_id', models.BigIntegerField(blank=True, default=0)),
                ('rules_channel_id', models.BigIntegerField(blank=True, default=0)),
                ('roles_channel_id', models.BigIntegerField(blank=True, default=0)),
                ('bot_log_channel_id', models.BigIntegerField(blank=True, default=0)),
                ('member_log_channel_id', models.BigIntegerField(blank=True, default=0)),
                ('update_log_channel_id', models.BigIntegerField(blank=True, default=0)),
                ('deterrence_log_channel_id', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_mail', models.BooleanField(default=False)),
                ('member', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('leave_date', models.DateTimeField(blank=True, default=None)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('coverimage', models.ImageField(upload_to='img/bgimgs')),
                ('rating', models.FloatField(blank=True, default=None)),
                ('label', models.CharField(max_length=100)),
                ('brief', models.TextField(default=None)),
                ('status', models.CharField(choices=[('cata red', 'Started'), ('cata green', 'Upcoming'), ('cata yellow', 'Completed'), ('cata purple', 'Refactoring')], default='Upcoming', max_length=16)),
                ('github', models.URLField(blank=True)),
                ('invite', models.URLField(blank=True)),
                ('commits', models.IntegerField(blank=True, default=0)),
                ('stars', models.IntegerField(blank=True, default=0)),
                ('forks', models.IntegerField(blank=True, default=0)),
                ('contributors', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('avatar', models.URLField(blank=True, default=None)),
                ('tag', models.CharField(max_length=6)),
                ('email', models.CharField(blank=True, default=None, max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('perks', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('name', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('message_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('brief', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('Under Review', 'R'), ('Approved', 'A'), ('Denied', 'D')], default='R', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=2000)),
                ('link', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_author', to='userdata.User')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_guild', to='userdata.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads', models.IntegerField(default=0)),
                ('spam', models.IntegerField(default=0)),
                ('bad_words', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='userdata.User')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('emoji_id', models.BigIntegerField(default=0)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='userdata.Guild')),
            ],
            options={
                'unique_together': {('id', 'emoji_id'), ('id', 'guild'), ('number', 'guild')},
            },
        ),
        migrations.CreateModel(
            name='MemberWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warned_member', to='userdata.Member')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to='userdata.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(blank=True, to='userdata.Role'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.User'),
        ),
        migrations.CreateModel(
            name='Infractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Short Mute', 'SM'), ('Long Temporary Mute', 'LM'), ('Kick', 'SK'), ('Short Temporary Ban', 'SB'), ('Long Temporary Ban', 'LB'), ('Permanent Ban', 'PB')], default='SM', max_length=30)),
                ('revoke_date', models.DateTimeField(default=None)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='userdata.Member')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infraction', to='userdata.MemberWarning')),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guild', models.ManyToManyField(to='userdata.Guild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.User')),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True)),
                ('name', models.CharField(default='Rule name', max_length=20)),
                ('statement', models.TextField(blank=True)),
                ('alias', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=utils.misc.empty_array, size=None)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_rule', to='userdata.Guild')),
            ],
            options={
                'unique_together': {('number', 'guild')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'guild')},
        ),
    ]
