# Generated by Django 3.0.7 on 2020-09-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(null=True, to='userdata.Role'),
        ),
    ]
