# Generated by Django 2.2.5 on 2019-12-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='mod_mail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
