# Generated by Django 3.0.7 on 2020-07-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20200708_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverutils',
            name='suggestions',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
