# Generated by Django 3.0.7 on 2020-10-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20201015_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='guild',
            field=models.ManyToManyField(null=True, to='userdata.Guild'),
        ),
    ]
