# Generated by Django 3.0.7 on 2020-10-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20201015_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='guild',
            field=models.ManyToManyField(to='userdata.Guild'),
        ),
    ]
