# Generated by Django 3.0.7 on 2020-09-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_role_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('id', 'emoji_id'), ('id', 'guild'), ('number', 'guild')},
        ),
        migrations.AlterUniqueTogether(
            name='rules',
            unique_together={('number', 'guild')},
        ),
    ]
