# Generated by Django 2.2.5 on 2019-12-19 19:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import userdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_auto_20191220_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='strikes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_strikes, null=True),
        ),
    ]
