# Generated by Django 3.0.7 on 2020-09-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_auto_20200929_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strike',
            name='member',
        ),
        migrations.AddField(
            model_name='strike',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='userdata.User'),
        ),
    ]
