# Generated by Django 3.0.7 on 2020-09-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_auto_20200926_2328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'guild')},
        ),
    ]
