# Generated by Django 3.0.7 on 2020-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_auto_20200926_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(blank=True, to='userdata.Role'),
        ),
    ]
