# Generated by Django 2.2.5 on 2019-12-19 19:42

import django.contrib.postgres.fields
from django.db import migrations, models
import userdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_auto_20191220_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='warnings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=userdata.models.default_array, null=True, size=None),
        ),
    ]
