# Generated by Django 3.0.7 on 2020-09-29 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_auto_20200930_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='userdata.User'),
        ),
    ]
