# Generated by Django 3.0.7 on 2020-09-30 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_auto_20200930_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_author', to='userdata.User'),
        ),
    ]
