# Generated by Django 2.2.5 on 2020-03-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_auto_20191220_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('coverimage', models.ImageField(upload_to='img/bgimgs')),
                ('rating', models.FloatField(blank=True, default=None)),
                ('label', models.CharField(default=None, max_length=100)),
                ('brief', models.TextField(default=None)),
                ('status', models.CharField(choices=[('cata yellow', 'Completed'), ('cata purple', 'Refactoring'), ('cata red', 'Started'), ('cata green', 'Upcoming')], default='Upcoming', max_length=16)),
                ('github', models.URLField(blank=True)),
                ('invite', models.URLField(blank=True)),
            ],
        ),
    ]
