# Generated by Django 3.0.7 on 2020-12-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_auto_20201029_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='brief',
            field=models.TextField(),
        ),
    ]
