# Generated by Django 3.0.7 on 2020-10-18 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_auto_20201019_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberwarning',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warned_member', to='userdata.Member'),
        ),
    ]
