# Generated by Django 2.2.5 on 2020-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0007_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='collaborators',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='commits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='forks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
