# Generated by Django 2.2.5 on 2020-03-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_auto_20200308_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='collaborators',
            new_name='contributors',
        ),
    ]
