# Generated by Django 2.2.5 on 2020-03-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0009_auto_20200309_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='activity',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
