# Generated by Django 2.2.5 on 2020-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0010_members_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
