# Generated by Django 2.2.5 on 2020-03-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0011_members_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='tag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
