# Generated by Django 2.2.5 on 2020-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0012_members_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='member',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
