# Generated by Django 2.2.5 on 2020-03-25 18:28

import django.contrib.postgres.fields
from django.db import migrations, models
import userdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0013_members_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=userdata.models.default_array, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='members',
            name='warnings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=userdata.models.default_array, null=True, size=None),
        ),
    ]
