# Generated by Django 2.2.5 on 2020-03-25 19:38

import django.contrib.postgres.fields
from django.db import migrations, models
import userdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0014_auto_20200325_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=userdata.models.default_array, null=True, size=None),
        ),
    ]
