# Generated by Django 2.2.5 on 2020-03-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0015_auto_20200326_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='tag',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
