# Generated by Django 2.2.5 on 2020-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0016_auto_20200327_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
