# Generated by Django 2.2.5 on 2020-04-09 16:16

import django.contrib.postgres.fields
from django.db import migrations, models
import userdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0017_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='alias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=userdata.models.default_array, null=True, size=None),
        ),
    ]
