# Generated by Django 2.2.5 on 2020-04-14 11:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import userdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0018_rules_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerUtils',
            fields=[
                ('guild_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('event_status', models.BooleanField(default=False)),
                ('bug_report', models.BooleanField(default=False)),
                ('mod_mail', models.BooleanField(default=False)),
                ('status', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_status, null=True)),
                ('Github_Micorservice', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_json, null=True)),
                ('Status_Microservice', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_json, null=True)),
                ('Tortoise_BOT', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_json, null=True)),
                ('Tortoise_BOT2', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_json, null=True)),
                ('Website', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_json, null=True)),
                ('Sockets', django.contrib.postgres.fields.jsonb.JSONField(default=userdata.models.default_json, null=True)),
            ],
        ),
    ]
