# Generated by Django 2.2.5 on 2020-04-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0019_serverutils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverutils',
            old_name='status',
            new_name='bot_status',
        ),
    ]
