# Generated by Django 2.2.5 on 2020-04-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0020_auto_20200414_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverutils',
            old_name='Github_Micorservice',
            new_name='Github_Microservice',
        ),
    ]
