# Generated by Django 2.2.5 on 2020-04-16 12:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import userdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0021_auto_20200414_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=6, null=True)),
                ('perks', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='serverutils',
            name='bot_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=userdata.models.default_status, null=True),
        ),
    ]
