# Generated by Django 2.2.5 on 2020-04-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0022_auto_20200416_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='activity',
        ),
    ]
