# Generated by Django 2.2.5 on 2020-04-16 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0023_remove_members_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmembers',
            name='id',
        ),
        migrations.AddField(
            model_name='topmembers',
            name='no',
            field=models.BigIntegerField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
