# Generated by Django 2.2.5 on 2020-04-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0024_auto_20200416_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmembers',
            name='no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
