# Generated by Django 2.2.5 on 2020-04-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0025_auto_20200416_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmembers',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topmembers',
            name='no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
