# Generated by Django 2.2.5 on 2020-04-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0026_auto_20200416_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=6, null=True)),
                ('perks', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('no', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TopMembers',
        ),
    ]
