# Generated by Django 2.2.5 on 2020-04-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0027_auto_20200416_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmember',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
