# Generated by Django 3.2.8 on 2021-10-31 13:46

import core.utils.misc
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', core.utils.misc.DiscordIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('suggestion_message_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('emotes', django.contrib.postgres.fields.ArrayField(base_field=core.utils.misc.DiscordIDField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_mail', models.BooleanField(default=False)),
                ('member', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('leave_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.guild')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.invite')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', core.utils.misc.DiscordIDField(primary_key=True, serialize=False)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.guild')),
            ],
            options={
                'unique_together': {('id', 'guild')},
            },
        ),
        migrations.CreateModel(
            name='SelfAssignableCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assignable_categories', to='api.guild')),
            ],
            options={
                'unique_together': {('name', 'guild')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', core.utils.misc.DiscordIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('tag', models.CharField(max_length=6)),
                ('avatar', models.URLField(blank=True, default='', max_length=150)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('email_verified', models.BooleanField(default=False)),
                ('perks', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('message_id', core.utils.misc.DiscordIDField(primary_key=True, serialize=False)),
                ('brief', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('R', 'Under Review'), ('A', 'Approved'), ('D', 'Denied')], default='R', max_length=20)),
                ('reason', models.CharField(blank=True, default='No reason specified.', max_length=2000)),
                ('link', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='api.member')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='api.guild')),
            ],
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads', models.PositiveSmallIntegerField(default=0)),
                ('spam', models.PositiveSmallIntegerField(default=0)),
                ('bad_words', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='MemberWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='api.member')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to='api.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(blank=True, to='api.Role'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='invite',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.member'),
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Mute'), ('K', 'Kick'), ('B', 'Ban')], max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='GuildRolesSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_role_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('verified_role_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('trusted_role_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('new_member_role', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roles_special', to='api.guild')),
            ],
        ),
        migrations.CreateModel(
            name='GuildOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_submission', models.BooleanField(default=False)),
                ('bug_report', models.BooleanField(default=False)),
                ('mod_mail', models.BooleanField(default=False)),
                ('suggestions', models.BooleanField(default=False)),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.guild')),
            ],
        ),
        migrations.CreateModel(
            name='GuildChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('announcements_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('react_for_roles_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('mod_mail_report_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('bug_reports_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('code_submissions_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('suggestions_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('system_log_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('deterrence_log_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('bot_log_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('successful_verifications_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('verification_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('member_count_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('general_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('rules_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('member_log_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('update_log_channel_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='api.guild')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guilds', models.ManyToManyField(to='api.Guild')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SelfAssignableRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_id', core.utils.misc.DiscordIDField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assignable_roles', to='api.selfassignablecategory')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
            options={
                'unique_together': {('order', 'category'), ('role', 'emoji_id')},
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=20)),
                ('statement', models.TextField()),
                ('alias', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=core.utils.misc.empty_array, size=None)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.guild')),
            ],
            options={
                'unique_together': {('number', 'guild')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'guild'), ('user', 'guild', 'invited_by')},
        ),
    ]
