name: Flake8 lint

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Display Python version
      run: python -c "import sys; print(f'Python version {sys.version}')"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pipenv
        python -m pipenv sync --dev
    - name: Lint with flake8
      run: python -m pipenv run lint
