# Generated by Django 3.0.7 on 2020-11-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortoise_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('cover_image', models.ImageField(upload_to='img/bgimgs')),
                ('rating', models.FloatField(blank=True, default=0.0)),
                ('label', models.CharField(max_length=100)),
                ('brief', models.TextField()),
                ('status', models.CharField(choices=[('cata red', 'Started'), ('cata green', 'Upcoming'), ('cata yellow', 'Completed'), ('cata purple', 'Refactoring')], default='cata purple', max_length=16)),
                ('github', models.URLField(blank=True)),
                ('invite', models.URLField(blank=True)),
                ('commits', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('stars', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('forks', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('contributors', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
        ),
    ]
